"""Convert the Blender delivery GLB to the simulator's OBJ coordinate contracts.

Usage: python tools/export_aircraft_obj.py assets/models/aircraft.glb
Requires numpy. Preserves linear PBR base colors, normals and material factors.
Only FIGHTER and MISSILE descendants are exported; studio objects are excluded.
"""
import argparse
import json
from pathlib import Path
import struct
import numpy as np


def export(source, destination, only=None, fighter_filename='jet.obj'):
    raw = Path(source).read_bytes()
    magic, version, length = struct.unpack_from('<4sII', raw)
    assert magic == b'glTF' and version == 2 and length == len(raw)
    offset = 12
    doc = data = None
    while offset < length:
        size, kind = struct.unpack_from('<II', raw, offset)
        chunk = raw[offset+8:offset+8+size]
        if kind == 0x4E4F534A:
            doc = json.loads(chunk)
        elif kind == 0x004E4942:
            data = chunk
        offset += 8+size
    assert doc is not None and data is not None

    def accessor(index):
        a = doc['accessors'][index]
        assert 'sparse' not in a, 'Sparse accessors are not supported'
        view = doc['bufferViews'][a['bufferView']]
        assert view.get('buffer', 0) == 0
        dtype = {5120:'i1',5121:'u1',5122:'<i2',5123:'<u2',5125:'<u4',5126:'<f4'}[a['componentType']]
        width = {'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4}[a['type']]
        item = np.dtype(dtype).itemsize
        start = view.get('byteOffset', 0)+a.get('byteOffset', 0)
        stride = view.get('byteStride', width*item)
        arr = np.ndarray((a['count'], width),dtype=dtype,buffer=data,offset=start,strides=(stride,item)).copy()
        if a.get('normalized') and a['componentType'] != 5126:
            info = np.iinfo(arr.dtype)
            arr = np.maximum(arr.astype(float)/info.max, -1)
        return arr

    def transform(node):
        if 'matrix' in node:
            return np.array(node['matrix']).reshape(4,4).T
        x,y,z,w = node.get('rotation',[0,0,0,1])
        rot = np.array([[1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w)],
                        [2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w)],
                        [2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)]])
        mat = np.eye(4)
        mat[:3,:3] = rot @ np.diag(node.get('scale',[1,1,1]))
        mat[:3,3] = node.get('translation',[0,0,0])
        return mat

    destination = Path(destination)
    destination.mkdir(parents=True, exist_ok=True)
    counts = {}
    for root_name, filename in [('FIGHTER',fighter_filename),('MISSILE','missile.obj')]:
        if only and root_name != only:
            continue
        roots = [i for i,n in enumerate(doc['nodes']) if n.get('name') == root_name or
                 (root_name == 'FIGHTER' and n.get('extras',{}).get('aircraft_id'))]
        assert len(roots) == 1, f'Missing or duplicated root: {root_name}'
        # glTF: X right, Y up, -Z forward. Jet loader rotates OBJ -90deg X;
        # target orientation expects local +Y forward, -Z up. Missile: +Y nose.
        axis = np.diag([1,1,-1]) if root_name == 'FIGHTER' else np.array([[1,0,0],[0,0,-1],[0,1,0]])
        lines = ['# Original MissileSim visual asset; Blender MCP authored.',
                 '# v x y z linear_r linear_g linear_b; # pbr metallic roughness',
                 '# Generated by tools/export_aircraft_obj.py']
        count = triangles = 0
        bounds = []
        throat_caps = []
        extras = doc['nodes'][roots[0]].get('extras',{})
        authored_sockets = extras.get('exhaust_sockets')
        if extras.get('aircraft_id'):
            # The renderer's proper-rotation basis has local X toward the
            # pilot's LEFT. Fleet Blender sources use X toward pilot's RIGHT.
            # Flip X as well as Z so asymmetric probes/lights stay on their
            # intended side. Historical source exports keep their old contract.
            axis = np.diag([-1,1,-1])
        if authored_sockets:
            for socket in json.loads(authored_sockets):
                x,y,z = socket['position']
                # Authoring Blender axes -> OBJ's pre-rotation coordinates.
                lines.append('# exhaust ' + ' '.join(f'{v:.7f}' for v in
                             (-x,z,y,0,0,-1,socket['radius'])))

        def visit(index, matrix):
            nonlocal count, triangles
            node = doc['nodes'][index]
            matrix = matrix @ transform(node)
            if 'mesh' in node:
                for prim in doc['meshes'][node['mesh']]['primitives']:
                    assert prim.get('mode',4) == 4
                    pos = accessor(prim['attributes']['POSITION'])
                    nrm = accessor(prim['attributes']['NORMAL'])
                    linear = axis @ matrix[:3,:3]
                    pos = pos @ linear.T + axis @ matrix[:3,3]
                    # Author attachment sockets from the actual outlet ring.
                    # They travel through the loader's exact mesh normalization.
                    node_name = node.get('name', '')
                    if not authored_sockets and ('nozzle interior' in node_name or 'hollow exhaust' in node_name):
                        axial = 2 if root_name == 'FIGHTER' else 1
                        ring = pos[np.abs(pos[:, axial] - pos[:, axial].min()) < 1e-5]
                        center = (ring.min(axis=0) + ring.max(axis=0)) * 0.5
                        radius = np.max(np.linalg.norm(ring - center, axis=1))
                        direction = np.zeros(3)
                        direction[axial] = -1
                        lines.append('# exhaust ' + ' '.join(f'{v:.7f}' for v in (*center, *direction, radius)))
                        if root_name == 'FIGHTER':
                            # Recess a dark throat behind the outlet lip. The
                            # source tube is open and its tailplane penetrates
                            # the deep cavity, so a rear view needs this baffle.
                            throat = np.unique(ring, axis=0).copy()
                            throat[:, axial] += radius * 0.2
                            throat_caps.append((node_name, throat, direction))
                    nrm = nrm @ np.linalg.inv(linear)
                    nrm /= np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True),1e-12)
                    assert np.isfinite(pos).all() and np.isfinite(nrm).all()
                    faces = (accessor(prim['indices']).ravel() if 'indices' in prim else np.arange(len(pos))).reshape(-1,3)
                    assert faces.min() >= 0 and faces.max() < len(pos)
                    if np.linalg.det(linear) < 0:
                        faces = faces[:,[0,2,1]]
                    # Degenerate exporter triangles have no visible area.
                    area = np.linalg.norm(np.cross(pos[faces[:,1]]-pos[faces[:,0]],pos[faces[:,2]]-pos[faces[:,0]]),axis=1)
                    faces = faces[area > 1e-12]
                    mat = doc['materials'][prim['material']].get('pbrMetallicRoughness',{})
                    color = np.array(mat.get('baseColorFactor',[1,1,1,1])[:3], dtype=float)
                    colors = np.tile(color,(len(pos),1))
                    if 'COLOR_0' in prim['attributes']:
                        colors *= accessor(prim['attributes']['COLOR_0'])[:,:3]
                    lines.append('o '+node.get('name','part').replace(' ','_'))
                    lines.append('# pbr %.6f %.6f'%(mat.get('metallicFactor',1),mat.get('roughnessFactor',1)))
                    lines.extend('v '+' '.join(f'{v:.7f}' for v in (*p,*c)) for p,c in zip(pos,colors))
                    lines.extend('vn '+' '.join(f'{v:.7f}' for v in n) for n in nrm)
                    lines.extend('f '+' '.join(f'{int(i)+count+1}//{int(i)+count+1}' for i in f) for f in faces)
                    count += len(pos)
                    triangles += len(faces)
                    bounds.extend([pos.min(axis=0),pos.max(axis=0)])
            for child in node.get('children',[]):
                visit(child,matrix)

        # Ignore presentation placement on the asset root, preserve child transforms.
        for child in doc['nodes'][roots[0]].get('children',[]):
            visit(child,np.eye(4))
        for name, ring, direction in throat_caps:
            center = (ring.min(axis=0) + ring.max(axis=0)) * 0.5
            ring = ring[np.argsort(np.arctan2(ring[:, 1] - center[1], ring[:, 0] - center[0]))]
            if np.dot(np.cross(ring[0] - center, ring[1] - center), direction) < 0:
                ring = ring[::-1]
            points = np.vstack([center, ring])
            lines += ['o ' + name.replace(' ', '_') + '_throat', '# pbr 0.15 0.82']
            lines.extend('v ' + ' '.join(f'{v:.7f}' for v in (*p, .012, .010, .008)) for p in points)
            lines.extend('vn ' + ' '.join(f'{v:.7f}' for v in direction) for _ in points)
            for i in range(len(ring)):
                face = (count + 1, count + i + 2, count + (i + 1) % len(ring) + 2)
                lines.append('f ' + ' '.join(f'{v}//{v}' for v in face))
            count += len(points)
            triangles += len(ring)
        assert count and triangles
        (destination/filename).write_text('\n'.join(lines)+'\n',encoding='utf-8')
        extent = np.max(bounds,axis=0)-np.min(bounds,axis=0)
        counts[filename] = {'vertices':count,'triangles':triangles,'extent':extent.tolist()}
    print(json.dumps(counts,indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source')
    parser.add_argument('--output',default='assets/models')
    parser.add_argument('--only',choices=['FIGHTER','MISSILE'],
                        help='Export one asset without replacing the other runtime model')
    parser.add_argument('--fighter-filename',default='jet.obj',
                        help='Per-aircraft runtime filename, e.g. rafale-c.obj')
    args = parser.parse_args()
    export(args.source,args.output,args.only,args.fighter_filename)
